-- CreateTable
CREATE TABLE "public"."ServiceCatalogItem" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT,
    "type" "public"."ROServiceType" NOT NULL DEFAULT 'LABOR',
    "labourHours" DECIMAL(10,2) NOT NULL DEFAULT 1,
    "unitPrice" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ServiceCatalogItem_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ServiceCatalogItem_category_idx" ON "public"."ServiceCatalogItem"("category");

-- Seed the managed catalog with the previously hardcoded service list.
-- labourHours defaults to 1 hr per item; adjust per service afterwards.
INSERT INTO "public"."ServiceCatalogItem"
  ("id", "name", "category", "type", "labourHours", "unitPrice", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid()::text, '80,000 Mile Service', 'Maintenance Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, '85 POINT INSPECTION 0104', 'Maintenance Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, '85,000 Mile Service', 'Maintenance Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, '90,000 Mile Service', 'Maintenance Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, '95,000 Mile Service', 'Maintenance Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'CHANGE OIL AND FILTER, 27 POINT INSPECTION & LUBRICATION 101', 'Maintenance Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/C COMPRESSOR & EVAPORATOR SERVICE & ODOUR CONTROL 2430', 'A/C Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/C Evacuate and Recharge', 'A/C Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/C Expansion Block/Orifice Tube', 'A/C Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/C Stepper Motor', 'A/C Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/C Suction Line', 'A/C Services', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/T - Accumulator', 'Transmission (A/T)', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/T - Band', 'Transmission (A/T)', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/T - Band Apply Servo', 'Transmission (A/T)', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/T - Band Apply Servo Switch', 'Transmission (A/T)', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/T - Band Control Solenoid Valve', 'Transmission (A/T)', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'A/T - Barometric Pressure Sensor', 'Transmission (A/T)', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'AdBlue Tank', 'AdBlue', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'AdBlue® Service', 'AdBlue', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Adjust and lubricate parking brake', 'Brakes', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Air Bag - Clockspring Assembly / Spiral Cable', 'Air Bag System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Air Bag - Control Module', 'Air Bag System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Air Bag - Diagnostic Connector', 'Air Bag System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Air Bag - Harness', 'Air Bag System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'After-Run Coolant Pump', 'Cooling System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'After-Run Coolant Solenoid Valve', 'Cooling System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'AIM HEADLIGHTS 2330', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp - High Beam Relay', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Adjusting Screw', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Alignment Actuator', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Alignment Control Module', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Alignment Sensor', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Alignment Switch', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Control Module', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Cover', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Dimmer Relay', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Dimmer Sensor', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Dimmer Switch', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Unit', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Washer Ambient Temperature Sensor', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Washer Hose', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Washer Motor', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Washer Motor Relay', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Washer Pump', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Washer Reservoir', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Washer Switch', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Wiper Arm', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Wiper Blade', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Headlamp Wiper Gear Box', 'Lighting / Headlamp', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Axle Beam Bushing', 'Axle / Suspension', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Axle Nut', 'Axle / Suspension', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Axle Replace - Front', 'Axle / Suspension', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Axle Seal', 'Axle / Suspension', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Ball Joint Replacement - Lower', 'Axle / Suspension', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Ball Joint Replacement - Upper', 'Axle / Suspension', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Backup Lamp Pigtail Assembly', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Backup Lamp Pigtail Socket', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Backup Lamp Relay', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery Cable End Replacement', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery Cable Replacement', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery Control Module', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery Current Sensor', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery fails performance test', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery Heater', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery New - Hybrid', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'BATTERY SERVICE - HIDDEN/SECONDARY BATTERY INSTALL BG ANTI CORROSION PADS 0831', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery Switch', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Battery Temperature Sensor', 'Electrical', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'BARO / MAP Sensor Switching Valve', 'Sensors', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Barometric Pressure Sensor', 'Sensors', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Barometric Pressure Switch', 'Sensors', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Catalytic Converter Gaskets', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Catalytic Converter Heat Shield', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Catalytic Converter Heat Shield Clamp', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Catalytic Converter Mounting Gasket', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Charcoal Canister', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'EVAP - Check Valve', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'EVAP - Evaporative Vapor Pressure Sensor', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'EVAP - Leak Detection Pump', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'EVAP - Leak Detection Valve', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'EVAP - Thermal Vacuum Valve', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Evap Canister Vent Valve', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Evap System Hose', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Evap System Vapor Line', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Exhaust', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Exhaust - Clamp', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Exhaust - Crossover Pipe', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Exhaust - Flange Gasket', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Exhaust - Pipe/Muffler Hanger', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ENVIRONMENTAL LEVY 1111', 'Exhaust / Emissions', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Crankcase Vent', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Crankcase Vent Valves', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Crankshaft', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Crankshaft Fluctuation Sensor', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Crankshaft Main Bearing Seal', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Crankshaft Sensor', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Accessory Bracket', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ENGINE BAY CLEAN 2319', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Control Module', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Coolant', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Coolant Temperature Sensor', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Cooling - Thermostat Gasket', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Guide Pulley', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ENGINE HOT OIL FLUSH DIESEL SERVICE INCLUDES PREMIUM OIL SERVICE AND FILTER CHANGE', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ENGINE HOT OIL FLUSH SERVICE INCLUDES PREMIUM OIL SERVICE AND FILTER CHANGE', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Mechanical Diagnostics 0901', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ENGINE MIL LIGHT ON - NO DRIVABILITY CONCERNS', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Rebuild/Replace', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ENGINE SHAMPOO 2342', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Tune Up', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Engine Wire Harness', 'Engine', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pressure Check Valve', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pressure Control Module', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pressure Pulsation Damper', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pressure Regulator', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pressure Regulator Seal', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pressure Release Valve', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pressure Relief Valve', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pressure Sensor', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pump - Oil Pressure Switch', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pump Access Cover', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fuel Pump Ballast Resistor Relay', 'Fuel System', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cruise Control - Distance Sensor', 'Cruise Control', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cruise Control - Module', 'Cruise Control', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cruise Control - Relay', 'Cruise Control', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cruise Control - Servo', 'Cruise Control', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cruise Control - Servo Cable', 'Cruise Control', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cruise Control - Switch', 'Cruise Control', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fan Clutch', 'Cooling Fan', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fan Control module', 'Cooling Fan', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fan Shroud', 'Cooling Fan', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fan/Drive Belt Replacement', 'Cooling Fan', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Center Console', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Center Console Lid', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Center Console Wood Grain', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Center Door Roller', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Exterior View Display Monitor', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fender Liner', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Flex Disk', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Flex Plate', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Floor Mats', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Floor Shifter Assembly', 'Interior / Body', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ESC Light', 'Stability / Electronics', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'ESP Control Module', 'Stability / Electronics', 'LABOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
