-- CreateTable
CREATE TABLE "public"."VehicleMake" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VehicleMake_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."VehicleModel" (
    "id" TEXT NOT NULL,
    "makeId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "VehicleModel_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "VehicleMake_name_key" ON "public"."VehicleMake"("name");

-- CreateIndex
CREATE INDEX "VehicleModel_makeId_idx" ON "public"."VehicleModel"("makeId");

-- CreateIndex
CREATE UNIQUE INDEX "VehicleModel_makeId_name_key" ON "public"."VehicleModel"("makeId", "name");

-- AddForeignKey
ALTER TABLE "public"."VehicleModel" ADD CONSTRAINT "VehicleModel_makeId_fkey" FOREIGN KEY ("makeId") REFERENCES "public"."VehicleMake"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Seed vehicle makes
INSERT INTO "public"."VehicleMake" ("id", "name", "createdAt", "updatedAt") VALUES
  (gen_random_uuid()::text, 'Acura', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Alfa Romeo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Aston Martin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Audi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'BMW', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Bentley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Buick', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Cadillac', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Chevrolet', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Chrysler', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Dodge', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Fiat', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Ford', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Genesis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'GMC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Honda', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Hyundai', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Infiniti', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Jaguar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Jeep', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Kia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Land Rover', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Lexus', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Lincoln', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Maserati', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Mazda', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Mercedes-Benz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Mini', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Mitsubishi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Nissan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Polestar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Porsche', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Ram', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Subaru', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Tesla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Toyota', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Volkswagen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Volvo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("name") DO NOTHING;

-- Seed vehicle models (joined to makes by name)
INSERT INTO "public"."VehicleModel" ("id", "makeId", "name", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, mk."id", src."model", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (VALUES
    ('Acura', 'CL'),
    ('Acura', 'ILX'),
    ('Acura', 'Integra'),
    ('Acura', 'Legend'),
    ('Acura', 'MDX'),
    ('Acura', 'NSX'),
    ('Acura', 'RDX'),
    ('Acura', 'RL'),
    ('Acura', 'RLX'),
    ('Acura', 'RSX'),
    ('Acura', 'TL'),
    ('Acura', 'TLX'),
    ('Acura', 'TSX'),
    ('Acura', 'ZDX'),
    ('Alfa Romeo', '4C'),
    ('Alfa Romeo', 'Giulia'),
    ('Alfa Romeo', 'Stelvio'),
    ('Alfa Romeo', 'Tonale'),
    ('Aston Martin', 'DB11'),
    ('Aston Martin', 'DB12'),
    ('Aston Martin', 'DBS'),
    ('Aston Martin', 'DBX'),
    ('Aston Martin', 'Vantage'),
    ('Audi', 'A3'),
    ('Audi', 'A4'),
    ('Audi', 'A5'),
    ('Audi', 'A6'),
    ('Audi', 'A7'),
    ('Audi', 'A8'),
    ('Audi', 'Q3'),
    ('Audi', 'Q4 e-tron'),
    ('Audi', 'Q5'),
    ('Audi', 'Q7'),
    ('Audi', 'Q8'),
    ('Audi', 'R8'),
    ('Audi', 'RS5'),
    ('Audi', 'RS7'),
    ('Audi', 'S3'),
    ('Audi', 'S4'),
    ('Audi', 'S5'),
    ('Audi', 'TT'),
    ('Audi', 'e-tron'),
    ('Audi', 'e-tron GT'),
    ('BMW', '2 Series'),
    ('BMW', '3 Series'),
    ('BMW', '4 Series'),
    ('BMW', '5 Series'),
    ('BMW', '6 Series'),
    ('BMW', '7 Series'),
    ('BMW', '8 Series'),
    ('BMW', 'X1'),
    ('BMW', 'X2'),
    ('BMW', 'X3'),
    ('BMW', 'X4'),
    ('BMW', 'X5'),
    ('BMW', 'X6'),
    ('BMW', 'X7'),
    ('BMW', 'Z4'),
    ('BMW', 'i4'),
    ('BMW', 'i5'),
    ('BMW', 'i7'),
    ('BMW', 'iX'),
    ('BMW', 'M2'),
    ('BMW', 'M3'),
    ('BMW', 'M4'),
    ('BMW', 'M5'),
    ('Bentley', 'Bentayga'),
    ('Bentley', 'Continental GT'),
    ('Bentley', 'Flying Spur'),
    ('Buick', 'Cascada'),
    ('Buick', 'Enclave'),
    ('Buick', 'Encore'),
    ('Buick', 'Encore GX'),
    ('Buick', 'Envision'),
    ('Buick', 'Envista'),
    ('Buick', 'LaCrosse'),
    ('Buick', 'Regal'),
    ('Buick', 'Verano'),
    ('Cadillac', 'ATS'),
    ('Cadillac', 'CT4'),
    ('Cadillac', 'CT5'),
    ('Cadillac', 'CT6'),
    ('Cadillac', 'CTS'),
    ('Cadillac', 'Escalade'),
    ('Cadillac', 'LYRIQ'),
    ('Cadillac', 'SRX'),
    ('Cadillac', 'XT4'),
    ('Cadillac', 'XT5'),
    ('Cadillac', 'XT6'),
    ('Cadillac', 'XTS'),
    ('Chevrolet', 'Blazer'),
    ('Chevrolet', 'Bolt EV'),
    ('Chevrolet', 'Bolt EUV'),
    ('Chevrolet', 'Camaro'),
    ('Chevrolet', 'Colorado'),
    ('Chevrolet', 'Corvette'),
    ('Chevrolet', 'Cruze'),
    ('Chevrolet', 'Equinox'),
    ('Chevrolet', 'Express'),
    ('Chevrolet', 'Impala'),
    ('Chevrolet', 'Malibu'),
    ('Chevrolet', 'Silverado 1500'),
    ('Chevrolet', 'Silverado 2500HD'),
    ('Chevrolet', 'Silverado 3500HD'),
    ('Chevrolet', 'Sonic'),
    ('Chevrolet', 'Spark'),
    ('Chevrolet', 'Suburban'),
    ('Chevrolet', 'Tahoe'),
    ('Chevrolet', 'Trailblazer'),
    ('Chevrolet', 'Traverse'),
    ('Chevrolet', 'Trax'),
    ('Chevrolet', 'Volt'),
    ('Chrysler', '200'),
    ('Chrysler', '300'),
    ('Chrysler', 'Aspen'),
    ('Chrysler', 'Pacifica'),
    ('Chrysler', 'PT Cruiser'),
    ('Chrysler', 'Sebring'),
    ('Chrysler', 'Town & Country'),
    ('Chrysler', 'Voyager'),
    ('Dodge', 'Avenger'),
    ('Dodge', 'Caliber'),
    ('Dodge', 'Challenger'),
    ('Dodge', 'Charger'),
    ('Dodge', 'Dart'),
    ('Dodge', 'Durango'),
    ('Dodge', 'Grand Caravan'),
    ('Dodge', 'Hornet'),
    ('Dodge', 'Journey'),
    ('Dodge', 'Nitro'),
    ('Dodge', 'Ram 1500'),
    ('Fiat', '124 Spider'),
    ('Fiat', '500'),
    ('Fiat', '500L'),
    ('Fiat', '500X'),
    ('Ford', 'Bronco'),
    ('Ford', 'Bronco Sport'),
    ('Ford', 'C-Max'),
    ('Ford', 'EcoSport'),
    ('Ford', 'Edge'),
    ('Ford', 'Escape'),
    ('Ford', 'Expedition'),
    ('Ford', 'Explorer'),
    ('Ford', 'F-150'),
    ('Ford', 'F-250'),
    ('Ford', 'F-350'),
    ('Ford', 'Fiesta'),
    ('Ford', 'Flex'),
    ('Ford', 'Focus'),
    ('Ford', 'Fusion'),
    ('Ford', 'Maverick'),
    ('Ford', 'Mustang'),
    ('Ford', 'Mustang Mach-E'),
    ('Ford', 'Ranger'),
    ('Ford', 'Taurus'),
    ('Ford', 'Transit'),
    ('Ford', 'Transit Connect'),
    ('Genesis', 'G70'),
    ('Genesis', 'G80'),
    ('Genesis', 'G90'),
    ('Genesis', 'GV60'),
    ('Genesis', 'GV70'),
    ('Genesis', 'GV80'),
    ('GMC', 'Acadia'),
    ('GMC', 'Canyon'),
    ('GMC', 'Hummer EV'),
    ('GMC', 'Savana'),
    ('GMC', 'Sierra 1500'),
    ('GMC', 'Sierra 2500HD'),
    ('GMC', 'Sierra 3500HD'),
    ('GMC', 'Terrain'),
    ('GMC', 'Yukon'),
    ('GMC', 'Yukon XL'),
    ('Honda', 'Accord'),
    ('Honda', 'Civic'),
    ('Honda', 'CR-V'),
    ('Honda', 'CR-Z'),
    ('Honda', 'Clarity'),
    ('Honda', 'Crosstour'),
    ('Honda', 'Element'),
    ('Honda', 'Fit'),
    ('Honda', 'HR-V'),
    ('Honda', 'Insight'),
    ('Honda', 'Odyssey'),
    ('Honda', 'Passport'),
    ('Honda', 'Pilot'),
    ('Honda', 'Prologue'),
    ('Honda', 'Ridgeline'),
    ('Hyundai', 'Accent'),
    ('Hyundai', 'Elantra'),
    ('Hyundai', 'Ioniq'),
    ('Hyundai', 'Ioniq 5'),
    ('Hyundai', 'Ioniq 6'),
    ('Hyundai', 'Kona'),
    ('Hyundai', 'Palisade'),
    ('Hyundai', 'Santa Cruz'),
    ('Hyundai', 'Santa Fe'),
    ('Hyundai', 'Sonata'),
    ('Hyundai', 'Tucson'),
    ('Hyundai', 'Veloster'),
    ('Hyundai', 'Venue'),
    ('Infiniti', 'EX35'),
    ('Infiniti', 'FX35'),
    ('Infiniti', 'G37'),
    ('Infiniti', 'Q50'),
    ('Infiniti', 'Q60'),
    ('Infiniti', 'Q70'),
    ('Infiniti', 'QX30'),
    ('Infiniti', 'QX50'),
    ('Infiniti', 'QX55'),
    ('Infiniti', 'QX60'),
    ('Infiniti', 'QX80'),
    ('Jaguar', 'E-Pace'),
    ('Jaguar', 'F-Pace'),
    ('Jaguar', 'F-Type'),
    ('Jaguar', 'I-Pace'),
    ('Jaguar', 'XE'),
    ('Jaguar', 'XF'),
    ('Jaguar', 'XJ'),
    ('Jeep', 'Cherokee'),
    ('Jeep', 'Compass'),
    ('Jeep', 'Gladiator'),
    ('Jeep', 'Grand Cherokee'),
    ('Jeep', 'Grand Wagoneer'),
    ('Jeep', 'Liberty'),
    ('Jeep', 'Patriot'),
    ('Jeep', 'Renegade'),
    ('Jeep', 'Wagoneer'),
    ('Jeep', 'Wrangler'),
    ('Kia', 'Carnival'),
    ('Kia', 'EV6'),
    ('Kia', 'EV9'),
    ('Kia', 'Forte'),
    ('Kia', 'K5'),
    ('Kia', 'Niro'),
    ('Kia', 'Optima'),
    ('Kia', 'Rio'),
    ('Kia', 'Sedona'),
    ('Kia', 'Seltos'),
    ('Kia', 'Sorento'),
    ('Kia', 'Soul'),
    ('Kia', 'Sportage'),
    ('Kia', 'Stinger'),
    ('Kia', 'Telluride'),
    ('Land Rover', 'Defender'),
    ('Land Rover', 'Discovery'),
    ('Land Rover', 'Discovery Sport'),
    ('Land Rover', 'Range Rover'),
    ('Land Rover', 'Range Rover Evoque'),
    ('Land Rover', 'Range Rover Sport'),
    ('Land Rover', 'Range Rover Velar'),
    ('Lexus', 'CT'),
    ('Lexus', 'ES'),
    ('Lexus', 'GS'),
    ('Lexus', 'GX'),
    ('Lexus', 'IS'),
    ('Lexus', 'LC'),
    ('Lexus', 'LS'),
    ('Lexus', 'LX'),
    ('Lexus', 'NX'),
    ('Lexus', 'RC'),
    ('Lexus', 'RX'),
    ('Lexus', 'RZ'),
    ('Lexus', 'UX'),
    ('Lincoln', 'Aviator'),
    ('Lincoln', 'Continental'),
    ('Lincoln', 'Corsair'),
    ('Lincoln', 'MKC'),
    ('Lincoln', 'MKS'),
    ('Lincoln', 'MKT'),
    ('Lincoln', 'MKX'),
    ('Lincoln', 'MKZ'),
    ('Lincoln', 'Nautilus'),
    ('Lincoln', 'Navigator'),
    ('Maserati', 'Ghibli'),
    ('Maserati', 'GranTurismo'),
    ('Maserati', 'Grecale'),
    ('Maserati', 'Levante'),
    ('Maserati', 'Quattroporte'),
    ('Mazda', 'CX-3'),
    ('Mazda', 'CX-30'),
    ('Mazda', 'CX-5'),
    ('Mazda', 'CX-50'),
    ('Mazda', 'CX-9'),
    ('Mazda', 'CX-90'),
    ('Mazda', 'MX-5 Miata'),
    ('Mazda', 'Mazda3'),
    ('Mazda', 'Mazda6'),
    ('Mazda', 'Tribute'),
    ('Mercedes-Benz', 'A-Class'),
    ('Mercedes-Benz', 'C-Class'),
    ('Mercedes-Benz', 'CLA'),
    ('Mercedes-Benz', 'CLS'),
    ('Mercedes-Benz', 'E-Class'),
    ('Mercedes-Benz', 'G-Class'),
    ('Mercedes-Benz', 'GLA'),
    ('Mercedes-Benz', 'GLB'),
    ('Mercedes-Benz', 'GLC'),
    ('Mercedes-Benz', 'GLE'),
    ('Mercedes-Benz', 'GLS'),
    ('Mercedes-Benz', 'S-Class'),
    ('Mercedes-Benz', 'SL'),
    ('Mercedes-Benz', 'SLC'),
    ('Mercedes-Benz', 'EQB'),
    ('Mercedes-Benz', 'EQE'),
    ('Mercedes-Benz', 'EQS'),
    ('Mini', 'Clubman'),
    ('Mini', 'Convertible'),
    ('Mini', 'Countryman'),
    ('Mini', 'Hardtop'),
    ('Mitsubishi', 'Eclipse Cross'),
    ('Mitsubishi', 'Lancer'),
    ('Mitsubishi', 'Mirage'),
    ('Mitsubishi', 'Outlander'),
    ('Mitsubishi', 'Outlander Sport'),
    ('Mitsubishi', 'RVR'),
    ('Nissan', '370Z'),
    ('Nissan', 'Altima'),
    ('Nissan', 'Ariya'),
    ('Nissan', 'Armada'),
    ('Nissan', 'Frontier'),
    ('Nissan', 'GT-R'),
    ('Nissan', 'Juke'),
    ('Nissan', 'Kicks'),
    ('Nissan', 'Leaf'),
    ('Nissan', 'Maxima'),
    ('Nissan', 'Murano'),
    ('Nissan', 'Pathfinder'),
    ('Nissan', 'Rogue'),
    ('Nissan', 'Sentra'),
    ('Nissan', 'Titan'),
    ('Nissan', 'Versa'),
    ('Nissan', 'Z'),
    ('Polestar', 'Polestar 2'),
    ('Polestar', 'Polestar 3'),
    ('Porsche', '718 Boxster'),
    ('Porsche', '718 Cayman'),
    ('Porsche', '911'),
    ('Porsche', 'Cayenne'),
    ('Porsche', 'Macan'),
    ('Porsche', 'Panamera'),
    ('Porsche', 'Taycan'),
    ('Ram', '1500'),
    ('Ram', '2500'),
    ('Ram', '3500'),
    ('Ram', 'ProMaster'),
    ('Ram', 'ProMaster City'),
    ('Subaru', 'Ascent'),
    ('Subaru', 'BRZ'),
    ('Subaru', 'Crosstrek'),
    ('Subaru', 'Forester'),
    ('Subaru', 'Impreza'),
    ('Subaru', 'Legacy'),
    ('Subaru', 'Outback'),
    ('Subaru', 'Solterra'),
    ('Subaru', 'WRX'),
    ('Tesla', 'Cybertruck'),
    ('Tesla', 'Model 3'),
    ('Tesla', 'Model S'),
    ('Tesla', 'Model X'),
    ('Tesla', 'Model Y'),
    ('Toyota', '4Runner'),
    ('Toyota', '86'),
    ('Toyota', 'Avalon'),
    ('Toyota', 'bZ4X'),
    ('Toyota', 'C-HR'),
    ('Toyota', 'Camry'),
    ('Toyota', 'Corolla'),
    ('Toyota', 'Corolla Cross'),
    ('Toyota', 'Crown'),
    ('Toyota', 'GR86'),
    ('Toyota', 'Highlander'),
    ('Toyota', 'Land Cruiser'),
    ('Toyota', 'Mirai'),
    ('Toyota', 'Prius'),
    ('Toyota', 'RAV4'),
    ('Toyota', 'Sequoia'),
    ('Toyota', 'Sienna'),
    ('Toyota', 'Supra'),
    ('Toyota', 'Tacoma'),
    ('Toyota', 'Tundra'),
    ('Toyota', 'Venza'),
    ('Toyota', 'Yaris'),
    ('Volkswagen', 'Arteon'),
    ('Volkswagen', 'Atlas'),
    ('Volkswagen', 'Atlas Cross Sport'),
    ('Volkswagen', 'Beetle'),
    ('Volkswagen', 'Golf'),
    ('Volkswagen', 'GTI'),
    ('Volkswagen', 'ID.4'),
    ('Volkswagen', 'Jetta'),
    ('Volkswagen', 'Passat'),
    ('Volkswagen', 'Taos'),
    ('Volkswagen', 'Tiguan'),
    ('Volkswagen', 'Touareg'),
    ('Volvo', 'C40'),
    ('Volvo', 'S60'),
    ('Volvo', 'S90'),
    ('Volvo', 'V60'),
    ('Volvo', 'V90'),
    ('Volvo', 'XC40'),
    ('Volvo', 'XC60'),
    ('Volvo', 'XC90')
) AS src("make", "model")
JOIN "public"."VehicleMake" mk ON mk."name" = src."make"
ON CONFLICT ("makeId", "name") DO NOTHING;
