name: Test Deploy

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: true
        default: 'Hello World'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: |
          echo "Test deployment workflow"
          echo "Message: ${{ inputs.message }}"
          echo "This is a simple test to verify workflow visibility"